// <auto-generated />
namespace EF_UseCases.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PhotographContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PhotographContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201904181213361_PhotographContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
